### ISSUE TITLE
用了nocheckvirt还是提醒不支持

### ISSUE THREAD

**Issue by DaisukiOshino** [tcp-nanqinlang/debian-kernel#1]
虚拟架构是Xen 改内核没问题 系统是Debian 9
用了tcp_nanqinlang-debiankernel-default-1.0.0.0-nocheckvirt.sh还是提醒[Error] only support KVM !
用backports没有这个问题 但是装完就开不了了

**Comment by nanqinlang** [comment]
手动注释 tcp_nanqinlang-debiankernel-default-1.0.0.0-nocheckvirt.sh 中的 check_kvm 项

**Comment by DaisukiOshino** [comment]
> 手动注释 tcp_nanqinlang-debiankernel-default-1.0.0.0-nocheckvirt.sh 中的 check_kvm 项

行 谢啦
